language: python
python:
- 3.8
- 3.7
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: abpwrs
  password:
    secure: pOfq1nXMKqI0/vml0QaVGyj8H8i3oxBBtmJohfUc1V4RcDjMmIRrRrwCYS6A3tYjyyZvpEIuWbSTfwc9RsuPorKQoK1QhuFsI0P+juBdGX0L3GDqxxcqSkL9jCfehsPL5UZuicMZgSQsMU5q2qcTc9PFqDlRBZAqNWIMk1stHGYeCLySrVkQs5yWpTRcKvVwNS3QCl8giPiIU1prfV+k4ynu+bHCu5rtI3bhrNmYh3ngUfolbohAYvIWJZ6B3FoQmC4b2trYS/Ft3yhOEDrXjNdRMM2Fp7rop1vKe35U2EnzWlulTn/AlGfqoTKYyNlX9n1FmT96pe75Rf7VOi3rnumVPS5AIFELOZL2ZgCkX5Kdww6Su5kmEy/+PshUv6OYTJshx7h96fjdLuv2KM8rHCBtVOW+zItC3ix9zTWQ4iLR4Y9JiQ3LZ5l9UMA0J1HX52OSgVdkY7JMcCdQNatD7PIQKbHqG1FrqTyQxn2JNupHxXLGbdXJg/K7eLbVFHB18SC9IahxT/otOXlCq2f5lQXYDSgxnKvZWz/csurWsQWW2J4aS7tVwSzR9XfOPzSpYGYj1Q09c3CCsda6QfcWfvPebJV+UKJkS3SN49zntONnheX6gQZ/tGlM4QTSVaHxfVkcA8sk2CFTBIt9igMTzuP4/7yFXwPv2EVcEeNWAOc=
  on:
    tags: true
    repo: abpwrs/slicerfiducials
    python: 3.8
